export const EMAIL_REGEX = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
export const ID_TOKEN_NAME = 'id'
export const REFRESH_TOKEN_NAME = 'refresh'
export const PASSWORD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[\^$*.\[\]{}\(\)?\-“!@#%&/,><\’:;|_~`])\S{8,20}$/
export const STRING_AND_SPACES_ONLY_REGEX =  /^[\w\s\-]+$/
export const BASE_URL = 'https://5f8hfugv1m.execute-api.us-east-1.amazonaws.com/prod'
export const IMAGE_UPLOAD_URL = '/tag'
export const QUERY_TAG_URL = '/tag/fetch'
export const STATIC_WEBSITE_BASE_URL = 'https://d23qfudvhy7ooe.cloudfront.net'